%\VignetteIndexEntry{Building the user guide from source}
\documentclass[12pt]{article}
\title{How to build the user guide from source}
\begin{document}
All the files for producing the user guide are included in the inst/doc directory.  However we have renamed the Makefiles to xxMakefile so that CRAN doesn't remake the user guide.  It takes awhile and requires some special style files and LaTeX packages (included in the doc directory).  If you want to rebuild the manual from source and remake the user guide, then remove the xx from the Makefile name for your system (Makefile for unix and Makefile.win for pc).

\end{document}

